### ISSUE TITLE
Question about your license

### ISSUE THREAD

**Issue by Poseidon281** [smashyalts/PterodactylModifications#5]
I would like to use a bit of your code in another project [Pelican](https://github.com/pelican-dev/panel?tab=AGPL-3.0-1-ov-file). I thought i would ask you if you would mind if i used a bit of your code in this project. Of course i will make adjustments, but i would like to build on your Dashboard

**Comment by smashyalts** [comment]
Curious what parts are you wanting to use in pelikan?, but should be fine as long as its gpl3 compliant ![Screenshot_20240526_232800_Chrome.jpg](https://github.com/smashyalts/PterodactylModifications/assets/47141527/d37cb4d4-ad68-4694-9395-632572517d4c)

**Comment by smashyalts** [comment]
Server sorting is already being implemented for example

**Comment by Poseidon281** [comment]
> Server sorting is already being implemented for example

Yes I know by me.

**Comment by Poseidon281** [comment]
> Curious what parts are you wanting to use in pelikan?, but should be fine as long as its gpl3 compliant.
> 
> 

This is my [PR](https://github.com/pelican-dev/panel/pull/276). So you can see that I used a little bit of your Dashboard.

**Comment by smashyalts** [comment]
Ah, sure its fine, not very great at licensing stuff, but its fine by me

**Comment by Poseidon281** [comment]
> Ah, sure its fine, not very great at licensing stuff, but its fine by me

Oké thanks

**Comment by smashyalts** [comment]
?

**Comment by Poseidon281** [comment]
Hello again, 

Thank you for allowing me to use your code as the basis for my PR. Just 1 thing that needs to be done. In order for the Pelican Team to add my code to the project since you are the original author of some it it you will need to sign the CLA. 

Could you do this? If so thanks you just need to make a PR in the project with some changes (which dont have to be legit you just have to make a PR in order to sign the CLA and then you can close it back up)then the bot will ask you to sign the CLA Agreement and once you have done that then my PR can be merged. 

It would be a great help if you can do this.

![image](https://github.com/smashyalts/PterodactylModifications/assets/62171904/423303c9-a024-47ca-bda1-4cf2d5e0f032)

**Comment by smashyalts** [comment]
https://github.com/pelican-dev/panel/pull/340

**Comment by Poseidon281** [comment]
Thanks I will leave this issue open if you don't mind in case the Pelican team has a few questions once my PR is merged (or closed). I will close it.

**Comment by smashyalts** [comment]
sure, no problem
